### PR TITLE
add timeframe option to change SSID only every recursion of that timeframe

### LINKED ISSUE #26: change SSID only after timeout
Bei einem schwach angebundenen Router, wenn die SSID sich ständig wechselt, macht es das schwer,  sich auf dem Router per Wlan zu verbinden, um auf der Konsole was zu ändern. Besser wäre, wenn sich die SSID erst nach einem Timeout von z.B. 5 Minuten zu offline ändern würde.

Dazu könnte man (nach https://github.com/ffac/gluon-ssid-changer/issues/4#issuecomment-173581235) eine var in `/tmp/count_ssid_off` schreiben (ram):

```
if [ ! -f /tmp/count_ssid_off ]; then 
  echo 0 > /tmp/count_ssid_off
fi
OFFCOUNT=$(cat /tmp/count_ssid_off)
let i=$(OFFCOUNT)+1 ; echo $i > /tmp/count_ssid_off
```

und statt immer gleich zu wechseln, einfach

```
TIMEOUT=5
if [ "$OFFCOUNT" -gt "$TIMEOUT" ]; then
  ... change SSID
fi
```

oder so ähnlich

### PR DESCRIPTION
**Pull request by rubo77**
closes #26

### CODE REVIEW

**Comment by mmalte** [comment]
If you want to run the skript only every n minutes, hours or days, you should just change the usr/lib/micron.d file in this repo.

**Comment by rubo77** [comment]
I think it wasn't clear, what I want to achieve here:

This PR just checks **every X minutes** if it should **set the SSID OFFLINE.**
still every minute the cron job runs and sets it **back online every minute** if the connection is back.

so this PR would give you the possibility to not to set the SSID OFFLINE everytime there is a short glitch.

Changing the cronjob to less often in /usr/lib/micron.d is not desireable, because then the node wouldnt switch back online directly when the connection is back

The standard is 1 Minute, so nothing changes to the default behaviour.

**So please reopen this PR.**

**Comment by mmalte** [comment]
Okay, by putting it back online every minute the functionality is much better than I first thought.

But short glitches are already caught by the Schmitt-Trigger.

This way it would be okay for me, but I would like it much better if it would store the number of tries with a low connection quality. That way you could choose to switch to the offline ssid after some tries and trigger a reboot after even more tries.

**Comment by rubo77** [comment]
good Idea, that could be implemented additionally to this PR independently in another PR. so If there is nothing wrong with this PR, this could already be merged?

**Pull request merged**
