### PR TITLE
gluon-ssid-changer: fix for batctl 2016.4+

### PR DESCRIPTION
**Pull request by rotanid**
this adjusts the grep for gateways so that it also works after updating to batctl 2016.4

### CODE REVIEW

**Comment by mmalte** [comment]
Thank you for adding this, I see no problem with the old version.

**Comment by rotanid** [comment]
just noticed: this was reverted one day later by #25 by @rubo77 *grrr
just a hint, fix it yourself for support of future gluon versions... @mmalte

**Comment by mmalte** [comment]
Thank you, I'm planning to add lede support in the next few weeks.

Right now I'm still testing new hardware with the plain Gluon master.

**Comment by rubo77** [comment]
I had no intention of reverting this, my PR was older than this one ;)

I recreated this PR in #31, cause this should work for the 2016.2.x branch too

**Pull request merged**
